[package]
name = "my-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "0.9.2"
shared = { path = "../shared" }

[dev_dependencies]
soroban-sdk = { version = "0.9.2", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
